### ISSUE TITLE
Android devices give 404 not found error when click on connect wallet button 

### ISSUE THREAD

**Issue by safaksonmez** [clxyder/walletconnect-expo-example#3]
@clxyder it works on ios when I connect with qr code but when I try to run with android simulator on my windows pc or qr code with my android device then click to connect wallet button browser opens and give 404 not found error.

**These are on android simulator**

![image](https://user-images.githubusercontent.com/40964682/162642216-2074bb08-1a6d-427e-ac01-7345e9cecf10.png)
![image](https://user-images.githubusercontent.com/40964682/162642226-cd5d1a77-f521-44e9-9019-9bd27a377e59.png)

**These are on my android device**

![image](https://user-images.githubusercontent.com/40964682/162642239-724c0e70-b982-4ebe-9475-0292e98f3c92.png)

**These are on my ios device**

![image](https://user-images.githubusercontent.com/40964682/162642255-f7d19640-5d63-49aa-923e-f2f0e0a67832.png)
![image](https://user-images.githubusercontent.com/40964682/162642259-1a6fe0be-7f87-46dc-9516-70b6efa41d50.png)
![image](https://user-images.githubusercontent.com/40964682/162642262-49edf79e-43d5-43d9-a439-75e6a1ee1356.png)
![image](https://user-images.githubusercontent.com/40964682/162642266-8985a716-a11b-41bf-aaec-17a4ff4e2ed4.png)
![image](https://user-images.githubusercontent.com/40964682/162642268-1cd3f0d3-3524-454e-9246-afd203974906.png)

**as you can see it works fine with ios but not working with android where am I mistaking ? I cloned the repo changed nothing.**

**Comment by clxyder** [comment]
Closing this issue as it was answered [HERE](https://github.com/cawfree/create-react-native-dapp/issues/30#issuecomment-1095025847).
