### ISSUE TITLE
Web version is keep refreshing

### ISSUE THREAD

**Issue by bdhcode** [clxyder/walletconnect-expo-example#4]
The web version is keep refreshing, you can reproduce this by starting expo with 'yarn start' and in the expo developer tools click 'Open in web browser'

**Comment by clxyder** [comment]
Hey @bdhcode that issue may be due to the changes made in `metro.config.js`. But I have not tested this for the web dev only mobile dev.

**Comment by bdhcode** [comment]
Hey @clxyder, is the global.ts needed in the web platform? because i think it is causing this problem, if you did a condition to require it only when the platform is not web the app works fine.

**Comment by clxyder** [comment]
Yea that might be causing issues because we are overriding certain properties that might not be necessary for web.

**Comment by clxyder** [comment]
Hey @bdhcode were you able to solve your issue? I just wanted to ask before closing the issue.

**Comment by bdhcode** [comment]
Of course i will create a pull request today

**Comment by clxyder** [comment]
Solve in #5
